@startuml
left to right direction
actor ユーザー
actor 管理者
rectangle ショッピングサイト{
	ユーザー-->(ログイン)
	ユーザー-->(購入)
	ユーザー-->(売却)
	ユーザー-->(商品閲覧)
	ユーザー-->(商品検索)
	(ログイン)<--管理者
	(商品閲覧)<--管理者
	(商品管理)<--管理者
	(注文管理)<--管理者
}
	(商品発送)<--管理者
@enduml